# Generated by Django 5.1.7 on 2025-05-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_booking_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
